title: my amazing course
tagline: A brand new course on Learning Lab
description: an amazing course
template:
  repo: my-amazing-course-template
  name: my-amazing-coursessss
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
    
steps:
  - title: First step
    description: The first step in your course
    event: issue_comment.created
    link: '{{ repoUrl }}'
    actions:
      - type: respond
        with: installed.md
        data:
          thePayload: '{{ payload }}'
